### ISSUE TITLE
Add NIC Driver Update to SNAPS-boot

### ISSUE THREAD

**Issue by rsku** [cablelabs/snaps-boot#110]
@RandyLevensalor 
If 'ip a' does not show any or all interfaces for the Intel X710 series NICs (used in the Purley servers) you need to update the driver.

Download the latest Intel driver [here](https://downloadcenter.intel.com/download/24411/Intel-Network-Adapter-Driver-for-PCIe-40-Gigabit-Ethernet-Network-Connections-Under-Linux-?product=95260)

Or a tar file is attached here:
[i40e-2.4.6.tar.gz](https://github.com/cablelabs/snaps-boot/files/2018709/i40e-2.4.6.tar.gz)
 
In the procedure below you can select a different directory than the user's home (~)
Copy the tar file to a USB stick.  Then on a fresh install of Ubuntu 16.04.4:
$ mkdir ~/i40e-drivers
$ sudo mkdir /media/usb
Insert usb stick, and verify usb dev name by 'sudo fdisk -l' before and after insert, probably the usb is listed as sdc1, and if so:
$ sudo mount /dev/sdc1 /media/usb
$ sudo cp /media/usb/i40e-2.4.6.tar.gz ~/i40e-drivers/
$ sudo apt-get update
$ sudo apt-get install gcc make
$ cd ~/i40e-drivers
$ tar zxvf i40e-2.4.6.tar.gz
$ cd i40e-2.4.6/src
$ make
$ sudo make install
$ sudo reboot now
after reboot
'ip a' should show all interfaces, including the 710 NIC interfaces
'ethtool -i enp175s0f0' (or any other interface) should show driver: i40e and version: 2.4.6

**Comment by dschrimpsher** [comment]
Added this to the initrd.gz (runtime and install) and to the snaps-boot instructions.  So this was closed as part of #90
