### ISSUE TITLE
Hugepage setting not quite right

### ISSUE THREAD

**Issue by bo-quan** [cablelabs/snaps-boot#151]
When testing DPDK in lab2, a couple of issues were found for hugepage settings:

1. Hugepage total size was set too small, need to increase the total hugepage sizes to at least 1/2 of total memory size an provide some guidance in the install guide;

2. A couple of settings for ubuntu are missing, causing huge page not functioning as expected (/sys/kernel/mm/transparent_hugepage/enabled and /sys/kernel/mm/transparent_hugepage/defrag should be [always] for hugepage to work.)

**Comment by RandyLevensalor** [comment]
I'd like to understand why we want to change to transparent hugepages.  I believe that there are some performance issues, especially with enabling defrag.

**Comment by bo-quan** [comment]
@RandyLevensalor You're right.  I'm going to close this issue in snaps-boot, and only change the default huge page sizes in snaps-config hosts.yaml files.

**Comment by bo-quan** [comment]
@RandyLevensalor You're right. I'm going to close this issue, and only change the default huge page sizes in hosts.yaml files.
