### ISSUE TITLE
Key injection not 100%.

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-boot#157]
Observed between 0 and 2 nodes without proper public key injection after cloud-init has completed

**Comment by bo-quan** [comment]
This was observed on bare metals, but no on virtual.

**Comment by bo-quan** [comment]
Steve had a workaround (playbook) for snaps-k8s for 16.04.4

**Comment by RandyLevensalor** [comment]
Fixed with digitalrebar patch
