### ISSUE TITLE
snaps-boot injects a 2nd key into id_rsa file if one already exists

### ISSUE THREAD

**Issue by bo-quan** [cablelabs/snaps-boot#221]
If one key already exists in .ssh/id_rsa file, snaps-boot injects a 2nd key into the same file which will not be imported properly.  snaps-boot should probably inject its key into its own key files, instead of using the well_known id_rsa file.

**Comment by spisarski** [comment]
This issue should no longer be an issue as we are no longer altering ~/id_rsa* files
