### ISSUE TITLE
ssh issue

### ISSUE THREAD

**Issue by bo-quan** [cablelabs/snaps-boot#266]
Currently it's not copying ssh key content (from snaps-boot.priv_key and snaps-boot.pub_key) to the well_known .ssh/ location (also existing entries in .ssh/known_hosts from previous deployment were not cleaned up or overridden), causing subsequent ansible play books to fail due to the ssh issue.

**Comment by spisarski** [comment]
This has been addressed by a different PR and the snaps-boot.*_key files are no longer
