### ISSUE TITLE
Change AWS CI to use spot instances

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-boot#272]
https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html

Spot instances cost about 1/4th the price for m5.metal when initially checked.

Just change ci/aws/aws-insts.tf

**Comment by bo-quan** [comment]
I tried it but ran into the following issue:

https://github.com/terraform-providers/terraform-provider-aws/issues/4313

**Comment by bo-quan** [comment]
Found a workaround by setting wait_for_fulfillment to true for the aws_spot_instance_request resource.
