### ISSUE TITLE
Checking and installing prerequisites should be done when script is launched

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-boot#41]
Incorporate this into the launcher script should also address any issues with the pre-requsits.  We can add an option to skip the check for doing installs faster.

Go to directory `snaps-boot/snaps-boot/`

Run `PreRequisite.sh` as shown below:

```
sudo ./PreRequisite.sh
```

If you see failuers or errors.  Update your software, remove obsolete
packages and reboot your server.
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get auto-remove
sudo reboot
```

**Comment by issi7915** [comment]
Created new script to check dependencies: pre_requistites.py in scripts directory. The iaas_launcher.py script will call the script upon launching. I suppose PreRequisites.sh can be deleted.

**Comment by bo-quan** [comment]
Shifting to digital rebar, closing this for now.
