### ISSUE TITLE
Update installation doc

### ISSUE THREAD

**Issue by medberry** [cablelabs/snaps-boot#63]
For instance:
 failuers or errors

check that doc for more typos then propose a solution.

**Comment by medberry** [comment]
opeartion typo in snaps-boot seen when running iaas_launch.py

**Comment by RandyLevensalor** [comment]
Let's use this as a general issue to track any new issues with the install doc.

**Comment by spisarski** [comment]
Please include that the PROVISION.PXE.password value must be > 7 characters. This value is currently not being checked before attempting to PXE boot but should as the ISO installation routine will hang waiting for user input for a valid password.
