### ISSUE TITLE
ssh key is not generated or copied

### ISSUE THREAD

**Issue by rainihixon** [cablelabs/snaps-boot#78]
the ssh key is not being generated or copied during setup/before it is necessary to use.  Could this be an issue with file/directories being moved?

**Comment by medberry** [comment]
Not sure but I concur. I have to go into root and ssh-copy-id to all of the hosts before the snaps-openstack step.

**Comment by medberry** [comment]
Looks the -b step doesn't set this as the -s (static) balks without this being set.

**Comment by medberry** [comment]
So this is working for me fine if I rerun the PXE command earlier in the install.md:

sudo -i python $PWD/iaas_launch.py -f $PWD/conf/pxe_cluster/hosts.yaml -p

verified repeatedly today. Never had to force the ssh keys over.
