### ISSUE TITLE
Add CentOS 7 support

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-boot#96]
Almost complete

**Comment by RandyLevensalor** [comment]
Targeting support by the end of March.

**Comment by chiraggupta06** [comment]
Hi Bo,

As discussed in the meeting, currently it's in Testing phase and will able to deliver it by next week.

Regards,
Chirag Gupta

**Comment by chiraggupta06** [comment]
Hi Bo,

A Pull request(Pxe centos support #104) has been created for supporting Centos Os in PXE. 

Regards,
Chirag Gupta
